/**
 * Demo product catalog — used as a fallback when the API is unreachable
 * (e.g. in standalone preview or dev mode without the backend).
 */

export const DEMO_PRODUCTS = [
  {
    _id: 'p1',
    name: 'Витамин D3 2000 IU',
    brand: 'Now Foods',
    category: 'vitamins',
    price: 185000,
    rating: 4.9,
    reviews: 248,
    volume: '120 капсул',
    isAvailable: true,
    isNew: true,
    description:
      'Витамин D3 в оптимальной дозировке для иммунитета, здоровья костей и энергии. Рекомендуется в осенне-зимний период.',
  },
  {
    _id: 'p2',
    name: 'Магний Бисглицинат',
    brand: 'Solgar',
    category: 'supplements',
    price: 245000,
    rating: 4.8,
    reviews: 182,
    volume: '90 таблеток',
    isAvailable: true,
    description:
      'Хелатная форма магния с высокой биодоступностью. Поддерживает нервную систему и качество сна.',
  },
  {
    _id: 'p3',
    name: 'Омега-3 Premium',
    brand: 'Carlson',
    category: 'supplements',
    price: 320000,
    rating: 4.7,
    reviews: 412,
    volume: '60 капсул',
    isAvailable: true,
    discount: 15,
    description:
      'Высокоочищенный рыбий жир из норвежских вод. EPA/DHA для сердца, мозга и суставов.',
  },
  {
    _id: 'p4',
    name: 'Цинк пиколинат 25 мг',
    brand: 'Thorne',
    category: 'vitamins',
    price: 165000,
    rating: 4.6,
    reviews: 94,
    volume: '60 капсул',
    isAvailable: true,
    description:
      'Легкоусваиваемая форма цинка. Поддержка иммунитета, кожи и репродуктивного здоровья.',
  },
  {
    _id: 'p5',
    name: 'Сыворотка для лица с витамином C',
    brand: 'The Ordinary',
    category: 'cosmetics',
    price: 135000,
    rating: 4.8,
    reviews: 528,
    volume: '30 мл',
    isAvailable: true,
    isNew: true,
    description:
      'Мощный антиоксидант. Выравнивает тон, осветляет пигментацию, стимулирует коллаген.',
  },
  {
    _id: 'p6',
    name: 'Увлажняющий крем Hydraboost',
    brand: 'Neutrogena',
    category: 'cosmetics',
    price: 98000,
    rating: 4.5,
    reviews: 201,
    volume: '50 мл',
    isAvailable: true,
    description:
      'Лёгкий гель-крем с гиалуроновой кислотой. 72 часа увлажнения без жирного блеска.',
  },
  {
    _id: 'p7',
    name: 'Коллаген Marine Type I',
    brand: 'Nordic Naturals',
    category: 'supplements',
    price: 385000,
    rating: 4.9,
    reviews: 173,
    volume: '300 г порошок',
    isAvailable: true,
    description:
      'Гидролизованный морской коллаген. Для кожи, волос, ногтей и суставов.',
  },
  {
    _id: 'p8',
    name: 'Шампунь Gentle Daily',
    brand: 'Weleda',
    category: 'hygiene',
    price: 72000,
    rating: 4.4,
    reviews: 88,
    volume: '200 мл',
    isAvailable: true,
    description:
      'Мягкий шампунь без сульфатов с органическим овсом. Для ежедневного ухода.',
  },
  {
    _id: 'p9',
    name: 'Кокосовая вода Organic',
    brand: 'Vita Coco',
    category: 'drinks',
    price: 24000,
    rating: 4.6,
    reviews: 156,
    volume: '330 мл',
    isAvailable: true,
    description:
      'Натуральный источник электролитов. Освежает и восстанавливает после тренировки.',
  },
  {
    _id: 'p10',
    name: 'Куркумин с пиперином',
    brand: 'Doctor\u2019s Best',
    category: 'supplements',
    price: 215000,
    rating: 4.7,
    reviews: 142,
    volume: '60 капсул',
    isAvailable: true,
    description:
      'Противовоспалительная поддержка. Биодоступная формула с биоперином для усвоения.',
  },
  {
    _id: 'p11',
    name: 'Мультивитамин Women',
    brand: 'Garden of Life',
    category: 'vitamins',
    price: 425000,
    rating: 4.8,
    reviews: 298,
    volume: '120 таблеток',
    isAvailable: true,
    discount: 10,
    description:
      'Полный комплекс из цельных пищевых продуктов для женщин — железо, фолат, B-комплекс.',
  },
  {
    _id: 'p12',
    name: 'Антисептик для рук',
    brand: 'Dr. Bronner',
    category: 'hygiene',
    price: 54000,
    rating: 4.3,
    reviews: 67,
    volume: '236 мл',
    isAvailable: false,
    description: 'Органический гель для рук с алоэ и эфирными маслами.',
  },
  {
    _id: 'p13',
    name: 'Аппарат для измерения давления',
    brand: 'Omron',
    category: 'parapharmaceuticals',
    price: 890000,
    rating: 4.9,
    reviews: 412,
    isAvailable: true,
    description:
      'Автоматический тонометр с индикатором аритмии и памятью на 90 измерений.',
  },
  {
    _id: 'p14',
    name: 'Термометр бесконтактный',
    brand: 'Braun',
    category: 'parapharmaceuticals',
    price: 425000,
    rating: 4.7,
    reviews: 203,
    isAvailable: true,
    isNew: true,
    description:
      'Инфракрасное измерение за 1 секунду. Память на 9 измерений, мягкий свет.',
  },
];
